"""Central task metadata enums and validation helpers."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

# A license_source pointer for a real (non-self_generated) license must be the
# upstream http(s) URL where the dataset license was confirmed, so a reviewer can
# verify provenance rather than trust a self-declared SPDX id.
_LICENSE_SOURCE_URL_RE = re.compile(r"^https?://", re.IGNORECASE)

TASK_TYPES: tuple[str, ...] = ("ml", "mujoco", "cfd", "structures")
REWARD_TYPES: tuple[str, ...] = (
    "continuous_scoring_function",
    "multi_deterministic_rubrics",
)
# Permissive licenses cleared for unrestricted commercial use AND derivative
# works. Copyleft / share-alike / non-commercial / research-only licenses are
# intentionally excluded: a task built on such data cannot ship in a commercial
# delivery, and a frontier LLM cannot reliably adjudicate that. Required for
# `ml` tasks, which routinely ship external datasets; mujoco/cfd/structures use
# solver-generated or self-authored data. SPDX identifiers; matched
# case-insensitively (see ``validate_license``).
LICENSES: tuple[str, ...] = (
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    "CC0-1.0",
    "CC-BY-4.0",
    "PDDL-1.0",
    "UPL-1.0",
)
LICENSE_REQUIRED_TASK_TYPES: tuple[str, ...] = ("ml",)
# Explicit escape hatch for tasks whose data is generated by the task itself
# (fully synthetic / self-authored data, or no third-party data at all), so no
# external dataset license applies. Accepted everywhere a license is, including
# to satisfy the ml requirement -- but it must be a deliberate choice, not a
# blank, and still needs a license_source justification for ml tasks.
LICENSE_SELF_GENERATED = "self_generated"
# Back-compat alias: "not_applicable" was the previous spelling of the
# self-generated escape hatch. Still accepted so existing tasks keep validating;
# new tasks and docs use "self_generated" (matches the reviewer criterion).
LICENSE_NOT_APPLICABLE = "not_applicable"
# Normalized set of accepted self-generated spellings (see normalize_enum_value).
_SELF_GENERATED_VALUES: frozenset[str] = frozenset(
    {LICENSE_SELF_GENERATED, LICENSE_NOT_APPLICABLE}
)
DOMAINS_BY_TASK_TYPE: dict[str, tuple[str, ...]] = {
    "ml": (
        "environmental_ecological_modeling",
        "education_language_cognitive_systems",
        "robotics_embodied_ai",
        "scientific_discovery_computational_science",
        "industrial_systems_manufacturing",
        "autonomous_systems_mobility",
        "healthcare_bioinformatics",
        "energy_climate_infrastructure",
        "financial_enterprise_forecasting",
        "multimodal_vision_perception",
        "reinforcement_learning_agentic_systems",
        "human_performance_sports_science",
        "communications_rf_signal_processing",
        "physical_sciences",
        "life_sciences",
        "medical_sciences_biochemistry",
        "engineering",
        "computer_science",
        "mathematics_statistics",
        "finance_economics",
        "earth_environmental_sciences",
        "social_sciences_humanities",
        "creative_arts_media",
        "physical_chemistry",
        "quantum_mechanics",
        "astrophysics",
        "geophysics",
        "optics_photonics",
        "high_energy_physics",
        "fluid_dynamics",
        "particle_physics",
        "proteomics",
        "agricultural_science",
        "neuroscience",
        "cell_biology",
        "ecology",
        "genomics",
        "clinical_prediction",
        "pharmacology",
        "epidemiology",
        "wearable_biosensor_data",
        "medical_imaging",
        "radiology",
        "manufacturing",
        "materials_science",
        "mechanical_engineering",
        "electrical_engineering",
        "energy_systems",
        "chemical_engineering",
        "aerospace_engineering",
        "civil_structural_engineering",
        "dynamical_systems",
        "combinatorics",
        "acoustics",
        "computer_vision",
        "cybersecurity",
        "software_engineering",
        "compiler_systems",
        "linguistics",
        "manipulation_grasping",
        "locomotion_mobility_aerial_systems",
        "robot_dynamics_system_identification",
        "robot_perception_policy_learning_coordination",
        "probability_statistics",
        "symbolic_regression",
        "atmospheric_science",
        "oceanography",
        "quantitative_finance",
        "risk_modeling",
        "macroeconomics",
        "insurance",
        "psychology",
        "urban_planning",
        "music",
        "world_models",
        "test_time_adaptation",
        "active_perception",
        "multimodal_sensor_fusion",
        "online_system_identification",
        "long_horizon_planning",
    ),
    "mujoco": (
        "policy_training_improvement",
        "model_environment_construction",
        "controller_planner_authoring",
        "debugging_reward_evaluation",
        "locomotion",
        "manipulation",
        "contact_rich_manipulation",
        "navigation_mobility",
        "balance_recovery",
        "assembly_contact_tasks",
        "disturbance_rejection",
        "morphology_design",
        "sensor_actuator_design",
        "underactuated_control",
        "multi_scenario_robustness",
        "swimming_aquatic_control",
        "wheeled_mobile_control",
        "humanoid_lite_control",
        "quadruped_control",
    ),
    "cfd": (
        "aerodynamics",
        "airfoil_design",
        "wing_planform_design",
        "flow_control",
        "vortex_suppression",
        "wake_dynamics",
        "boundary_layer_modeling",
        "turbulence_modeling",
        "mesh_generation",
        "cfd_case_repair",
        "pressure_distribution_matching",
        "vlm_trim_analysis",
        "xfoil_polar_optimization",
        "rans_simulation",
        "high_order_cfd",
        "gpu_lattice_boltzmann",
    ),
    "structures": (
        "seismic_retrofit",
        "structural_mechanics",
        "topology_optimization",
        "truss_design",
        "frame_analysis",
        "beam_sizing",
        "buckling_analysis",
        "modal_analysis",
        "stress_displacement_analysis",
        "load_path_optimization",
        "finite_element_model_repair",
        "continuum_mechanics",
        "density_field_optimization",
        "support_member_repair",
        "mass_compliance_optimization",
    ),
}

CONTINUOUS_GROUND_TRUTH_TARGET = 0.5
CONTINUOUS_GROUND_TRUTH_EPSILON = 0.05
DETERMINISTIC_GROUND_TRUTH_TARGET = 1.0


@dataclass(frozen=True)
class GroundTruthScoreExpectation:
    """Expected score target for the oracle/reference solution."""

    target: float
    epsilon: float
    reward_type: str

    @property
    def description(self) -> str:
        if self.reward_type == "continuous_scoring_function":
            return f"{self.target:.1f} ± {self.epsilon:g}"
        return f"{self.target:.1f}"

    def passed(self, score: float) -> bool:
        return abs(score - self.target) <= self.epsilon


def normalize_enum_value(value: object) -> str:
    return str(value or "").strip().lower().replace("-", "_")


def validate_task_type(value: object) -> list[str]:
    task_type = normalize_enum_value(value)
    if not task_type:
        return ["task.toml [difficulty].task_type is required"]
    if task_type not in TASK_TYPES:
        return [
            "task.toml [difficulty].task_type must be one of "
            f"{list(TASK_TYPES)}; got {task_type!r}"
        ]
    return []


def validate_reward_type(value: object) -> list[str]:
    reward_type = normalize_enum_value(value)
    if not reward_type:
        return ["task.toml [difficulty].reward_type is required"]
    if reward_type not in REWARD_TYPES:
        return [
            "task.toml [difficulty].reward_type must be one of "
            f"{list(REWARD_TYPES)}; got {reward_type!r}"
        ]
    return []


def validate_domain(task_type_value: object, domain_value: object) -> list[str]:
    task_type = normalize_enum_value(task_type_value)
    domain = normalize_enum_value(domain_value)
    if not domain:
        return ["task.toml [difficulty].domain is required"]
    if task_type not in DOMAINS_BY_TASK_TYPE:
        return []
    valid = DOMAINS_BY_TASK_TYPE[task_type]
    if domain not in valid:
        return [
            "task.toml [difficulty].domain must be one of "
            f"{list(valid)} for task_type {task_type!r}; got {domain!r}"
        ]
    return []


def validate_license(
    task_type_value: object,
    license_value: object,
    license_source_value: object = "",
) -> list[str]:
    """Validate the dataset license and its provenance pointer.

    Required when ``task_type`` is in ``LICENSE_REQUIRED_TASK_TYPES`` (currently
    ``ml``); optional otherwise.

    ``license`` accepts a permissive SPDX id from :data:`LICENSES`, or
    :data:`LICENSE_SELF_GENERATED` (``"self_generated"``) as an explicit escape
    hatch for data the task generates itself (synthetic / self-authored, or no
    third-party data at all). ``"not_applicable"`` is accepted as a back-compat
    alias. Matching is case-insensitive and hyphen/underscore-insensitive so
    authors can write the natural SPDX id (``Apache-2.0``) in ``task.toml``.

    ``license_source`` is the author-supplied provenance pointer the licensing
    reviewer verifies by hand (the human sign-off is the code-owner PR approval,
    not a self-declared field):

    * for a real license -- the upstream-most http(s) URL where the license was
      confirmed (HF/Kaggle mirrors routinely carry wrong claims);
    * for ``self_generated`` -- a short written reason the data is generated by
      the task itself and no external license applies.

    Only enforced for ``ml`` tasks; a no-op otherwise.
    """
    task_type = normalize_enum_value(task_type_value)
    license_id = normalize_enum_value(license_value)
    if not license_id:
        if task_type in LICENSE_REQUIRED_TASK_TYPES:
            return [
                "task.toml [difficulty].license is required when task_type is "
                f"{task_type!r}; must be one of {list(LICENSES)} (or "
                f"{LICENSE_SELF_GENERATED!r} for data the task generates itself)"
            ]
        return []
    allowed = {normalize_enum_value(value) for value in LICENSES}
    allowed |= _SELF_GENERATED_VALUES
    if license_id not in allowed:
        return [
            "task.toml [difficulty].license must be a permissive license, one of "
            f"{list(LICENSES)} (or {LICENSE_SELF_GENERATED!r} for self-generated "
            f"data); got {license_value!r}"
        ]

    # Provenance pointer: only required for license-bearing task types (ml). This
    # is what the code-owner licensing reviewer checks; it is intentionally a
    # single free-form field (URL or justification), not a bespoke schema.
    if task_type not in LICENSE_REQUIRED_TASK_TYPES:
        return []
    is_self_generated = license_id in _SELF_GENERATED_VALUES
    source = str(license_source_value or "").strip()
    if not source:
        if is_self_generated:
            return [
                "task.toml [difficulty].license_source is required when license is "
                f"{LICENSE_SELF_GENERATED!r}: briefly state how the task generates "
                "its own data (e.g. synthetic data produced by solution/generate.py)."
            ]
        return [
            "task.toml [difficulty].license_source is required for ml tasks: the "
            "upstream http(s) URL where the dataset license was confirmed, so a "
            "reviewer can verify provenance (the self-declared license is not "
            "sufficient on its own)."
        ]
    if not is_self_generated and not _LICENSE_SOURCE_URL_RE.match(source):
        return [
            "task.toml [difficulty].license_source must be the upstream http(s) URL "
            f"where the license was confirmed; got {license_source_value!r}"
        ]
    return []


def expected_ground_truth_score(
    reward_type_value: object,
    *,
    deterministic_epsilon: float,
    continuous_epsilon: float = CONTINUOUS_GROUND_TRUTH_EPSILON,
) -> GroundTruthScoreExpectation:
    reward_type = normalize_enum_value(reward_type_value)
    if reward_type == "continuous_scoring_function":
        return GroundTruthScoreExpectation(
            target=CONTINUOUS_GROUND_TRUTH_TARGET,
            epsilon=continuous_epsilon,
            reward_type=reward_type,
        )
    if reward_type != "multi_deterministic_rubrics":
        raise ValueError(
            "task.toml [difficulty].reward_type must be one of "
            f"{list(REWARD_TYPES)}; got {reward_type!r}"
        )
    return GroundTruthScoreExpectation(
        target=DETERMINISTIC_GROUND_TRUTH_TARGET,
        epsilon=deterministic_epsilon,
        reward_type=reward_type,
    )


def metadata_validation_issues(
    *,
    task_type: Any,
    domain: Any,
    reward_type: Any,
    license_id: Any = "",
    license_source: Any = "",
) -> list[str]:
    issues: list[str] = []
    issues.extend(validate_task_type(task_type))
    issues.extend(validate_domain(task_type, domain))
    issues.extend(validate_reward_type(reward_type))
    issues.extend(validate_license(task_type, license_id, license_source))
    return issues
